// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-site-info.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_site_info_default = defineTool({
  name: "get_site_info",
  title: "Get TokenBel site info",
  description: "Return basic information about TokenBel: description, main sections, and key external URLs (dashboard, API, wiki).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify(
          {
            name: "TokenBel",
            description: "\u0410\u0433\u0440\u0435\u0433\u0430\u0442\u043E\u0440 \u0438\u043D\u0432\u0435\u0441\u0442\u0438\u0446\u0438\u043E\u043D\u043D\u044B\u0445 \u0442\u043E\u043A\u0435\u043D\u043E\u0432 \u0438 \u0446\u0435\u043D\u043D\u044B\u0445 \u0431\u0443\u043C\u0430\u0433 \u0411\u0435\u043B\u0430\u0440\u0443\u0441\u0438: \u043A\u0430\u0442\u0430\u043B\u043E\u0433 \u0442\u043E\u043A\u0435\u043D\u043E\u0432 \u0438 \u044D\u043C\u0438\u0442\u0435\u043D\u0442\u043E\u0432, \u0441\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043A\u0430 \u0432\u0442\u043E\u0440\u0438\u0447\u043D\u043E\u0433\u043E \u0440\u044B\u043D\u043A\u0430, \u0430\u043D\u0430\u043B\u0438\u0442\u0438\u043A\u0430 \u0434\u043E\u0445\u043E\u0434\u043D\u043E\u0441\u0442\u0438.",
            language: "ru-BY",
            urls: {
              landing: "https://tokenbel.info",
              dashboard: "https://dashboard.tokenbel.info",
              api: "https://hype.tokenbel.info",
              wiki: "https://wiki.tokenbel.info",
              rss: "https://tokenbel.info/rss/",
              faq: "https://tokenbel.info/faq/",
              pricing: "https://tokenbel.info/pricing/",
              statistics: "https://tokenbel.info/statistics/secondmarket/"
            }
          },
          null,
          2
        )
      }
    ]
  })
});

// src/lib/mcp/tools/search-securities.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var API_BASE = "https://hype.tokenbel.info";
var search_securities_default = defineTool2({
  name: "search_securities",
  title: "Search Belarusian securities",
  description: "Search Belarusian tokens, shares and bonds by ticker or issuer name via the TokenBel public Hype API.",
  inputSchema: {
    query: z.string().min(1).describe("Ticker fragment or issuer name to search for."),
    limit: z.number().int().min(1).max(50).describe("Maximum number of results to return (1-50).").default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ query, limit }) => {
    const url = `${API_BASE}/search?q=${encodeURIComponent(query)}&limit=${limit}`;
    try {
      const res = await fetch(url, { headers: { Accept: "application/json" } });
      const text = await res.text();
      if (!res.ok) {
        return {
          content: [{ type: "text", text: `Hype API error ${res.status}: ${text.slice(0, 500)}` }],
          isError: true
        };
      }
      return { content: [{ type: "text", text }] };
    } catch (err) {
      return {
        content: [{ type: "text", text: `Request failed: ${err.message}` }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "tokenbel-mcp",
  title: "TokenBel MCP",
  version: "0.1.0",
  instructions: "Tools for TokenBel \u2014 Belarusian securities & tokens aggregator. Use `get_site_info` for platform overview and `search_securities` to look up tokens, shares or bonds by ticker or issuer.",
  tools: [get_site_info_default, search_securities_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
